platform: linux

inputs:
- name: korifi-release-version
- name: korifi-ci
- name: korifi

outputs:
- name: korifi

params:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:
  CLUSTER_TYPE:
  REGISTRY_HOSTNAME:
  REGISTRY_USER:
  REGISTRY_PASSWORD:


run:
  path: korifi-ci/pipelines/scripts/create-release.sh
