#!/bin/bash

set -euo pipefail

cat <<EOF >clusters/env_vars.yaml
AWS_REGION: $AWS_REGION
CLUSTER_NAME: $CLUSTER_NAME
CLUSTER_TYPE: $CLUSTER_TYPE
GCP_PROJECT_ID: $GCP_PROJECT_ID
GCP_ZONE: $GCP_ZONE
NODE_MACHINE_TYPE: $NODE_MACHINE_TYPE
USE_LETSENCRYPT: ${USE_LETSENCRYPT:-}
CI_REPO_LOCATION: ${CI_REPO_LOCATION}
CI_REPO_NAME: ${CI_REPO_NAME}
KPACK_REPO_LOCATION: ${KPACK_REPO_LOCATION}
KPACK_REPO_NAME: ${KPACK_REPO_NAME}
EOF
