#!/bin/bash

gcloud-login() {
  declare -r service_account_json="/tmp/service-account.json"
  echo "$GCP_SERVICE_ACCOUNT_JSON" >"$service_account_json"
  gcloud auth activate-service-account --key-file="$service_account_json"
  gcloud config set container/use_application_default_credentials true
}

export-kubeconfig() {
  declare -r name=$1
  gcloud container clusters get-credentials "$name" --zone "$GCP_ZONE"
}
