#!/bin/bash

gcloud-login() {
  declare -r service_account_json="/tmp/service-account.json"
  echo "$GCP_SERVICE_ACCOUNT_JSON" >"$service_account_json"
  gcloud auth activate-service-account --key-file="$service_account_json"
  gcloud config set container/use_application_default_credentials true
}

export-kubeconfig() {
  gcloud-login
  echo "$GCP_SERVICE_ACCOUNT_JSON" >"/tmp/sa.json"
  export GOOGLE_APPLICATION_CREDENTIALS="/tmp/sa.json"

  case "$CLUSTER_TYPE" in
    "GKE")
      gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$GCP_ZONE"
      ;;
    "EKS")
      aws eks update-kubeconfig --region "$AWS_REGION" --name "$CLUSTER_NAME"
      ;;
    *)
      echo "Invalid CLUSTER_TYPE: $CLUSTER_TYPE"
      echo "Valid values are: EKS, GKE"
      exit 1
      ;;
  esac
}
