#!/bin/bash

docker_login() {
  kubectl delete secret buildkit &>/dev/null || true
  kubectl create secret docker-registry buildkit --docker-server="https://$REGISTRY_HOSTNAME/v1/" \
    --docker-username="$REGISTRY_USER" --docker-password="$REGISTRY_PASSWORD"

  export KBLD_REGISTRY_HOSTNAME="$REGISTRY_HOSTNAME"
  export KBLD_REGISTRY_USERNAME="$REGISTRY_USER"
  export KBLD_REGISTRY_PASSWORD="$REGISTRY_PASSWORD"
}

build-korifi() {
  kbld -f "$KBLD_CONFIG_DIR/korifi-kbld.yml" -f "$VALUES_BASE/values.yaml"
}
